module.exports = {
  add: require('./src/math/add'),
  div: require('./src/math/divide'),
  mul: require('./src/math/multiply'),
  sub: require('./src/math/subtract'),

  allPass   : require('./src/logic/allPass'),
  anyPass   : require('./src/logic/anyPass'),
  both      : require('./src/logic/both'),
  either    : require('./src/logic/either'),
  complement: require('./src/logic/complement'),
  either    : require('./src/logic/either'),
  equal     : require('./src/logic/equal'),
  gt        : require('./src/logic/greaterThan'),
  gte       : require('./src/logic/greaterThanOrEqual'),
  ifElse    : require('./src/logic/ifElse'),
  lt        : require('./src/logic/lessThan'),
  lte       : require('./src/logic/lessThanOrEqual'),
  unless    : require('./src/logic/unless'),
  when      : require('./src/logic/when'),

  always  : require('./src/function/always'),
  compose : require('./src/function/compose'),
  curry   : require('./src/function/curry'),
  flip    : require('./src/function/flip'),
  identity: require('./src/function/identity'),
  pipe    : require('./src/function/pipe'),
  __      : require('./src/function/placeholderArgument'),
  thunkify: require('./src/function/thunkify'),

  filter: require('./src/list/filter'),
  map   : require('./src/list/map'),
  reduce: require('./src/list/reduce'),
};
