export { default as all }         from './all';
export { default as any }         from './any';
export { default as concatA }     from './concat';
export { default as filter }      from './filter';
export { default as join }        from './join';
export { default as map }         from './map';
export { default as reduce }      from './reduce';
export { default as reduceWhile } from './reduceWhile';
export { default as slice }       from './slice';
